spring:
  application:
    name: codereviewer
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

github:
  token: ${GITHUB_TOKEN}
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}

google:
  gemini:
    api-key: ${GOOGLE_GEMINI_API_KEY}
    model: ${GOOGLE_GEMINI_MODEL:gemini-flash-latest}

# do not include stacktrace, binding errors etc. in API responses.
server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
